server:
  port: 8080
  host: localhost

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  dbname: task_scheduler

redis:
  host: localhost
  port: 6379
  password: ""

kafka:
  brokers:
    - localhost:9092
  topic: tasks

etcd:
  endpoints:
    - localhost:2379
  dialTimeout: 5s

worker:
  count: 5

logging:
  level: info
  format: json